spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s
        wiretap: true # logging.level.reactor.netty.http.client: TRACE or DEBUG
      httpserver:
        wiretap: true # logging.level.reactor.netty.http.server: TRACE or DEBUG
      routes:
        - id: creditrating
          uri: lb://creditrating
          predicates:
            - Path=/api/coffeeshop/creditrating/**
        - id: location
          uri: lb://location
          predicates:
            - Path=/api/coffeeshop/nearest/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/coffeeshop/*/order
        - id: order-get
          uri: lb://order
          predicates:
            - Path=/api/coffeeshop/*/order/**
        - id: order-menu
          uri: lb://order
          predicates:
            - Path=/api/coffeeshop/menu/**
        - id: creditrating-apidocs
          uri: lb://creditrating
          predicates:
            - Path=/apidocs/creditrating/**
          filters:
            - StripPrefix=2
            - RewritePath=/v3/api-docs/[^/]+$\, /v3/api-docs
        - id: location-apidocs
          uri: lb://location
          predicates:
            - Path=/apidocs/location/**
          filters:
            - StripPrefix=2
            - RewritePath=/v3/api-docs/[^/]+$\, /v3/api-docs
        - id: order-apidocs
          uri: lb://order
          predicates:
            - Path=/v3/api-docs/order
          filters:
            #- StripPrefix=2
            #- RewritePath=/apidocs/order/v3/api-docs/[^/]+$\, /v3/api-docs
            #- SetPath=/v3/api-docs
            #- RewritePath=/v3/api-docs/(?<path>.*), /v3/api-docs
            - RewritePath=/v3/api-docs/order, /v3/api-docs
